/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Graphics;

/**
 *
 * @author 348676487
 */
public class Panel extends javax.swing.JPanel {

    /**
     * Creates new form Panel
     */
    public Panel() {
        initComponents();
    }

    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        hTree(g, 4, this.getWidth() / 2, this.getHeight() / 2, 200);
    }

    public void hTree(Graphics g, int n, int x, int y, int size) {
        //Draw an h shape
        hShape(g, x, y, size);
        //Recurse until n is 0
        if (n > 0) {
            //bottom-left
            hTree(g, n - 1, x - size / 2, y + size / 2, size / 2);
            //top-left
            hTree(g, n - 1, x - size / 2, y - size / 2, size / 2);
            //bottom-right
            hTree(g, n - 1, x + size / 2, y + size / 2, size / 2);
            //top-right
            hTree(g, n - 1, x + size / 2, y - size / 2, size / 2);
        }
    }

    public void hShape(Graphics g, int x, int y, int size) {
        //center
        g.drawLine(x - size / 2, y, x + size / 2, y);
        //left vertical
        g.drawLine(x - size / 2, y + size / 2, x - size / 2, y - size / 2);
        //right vertical
        g.drawLine(x + size / 2, y + size / 2, x + size / 2, y - size / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
